export const SQL_SETUP_SCRIPT = `
-- 1. Create PROFILES table
create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  avatar_url text,
  rank text default 'common',
  sub_rank text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Enable RLS on Profiles
alter table public.profiles enable row level security;

-- 3. Profiles Policies
create policy "Public profiles are viewable by everyone." on public.profiles for select using ( true );
create policy "Users can insert their own profile." on public.profiles for insert with check ( auth.uid() = id );
create policy "Users can update own profile." on public.profiles for update using ( auth.uid() = id );

-- 4. Create ADMIN_REQUESTS table
create table if not exists public.admin_requests (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id),
  full_name text,
  email text,
  type text default 'Admin Access',
  status text default 'Pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Enable RLS on Admin Requests
alter table public.admin_requests enable row level security;

-- 6. Admin Requests Policies
create policy "Users can create requests." on public.admin_requests for insert with check ( auth.uid() = user_id );
create policy "Users can view their own requests." on public.admin_requests for select using ( auth.uid() = user_id );

-- 7. GOD Mode Policies (Poseidon Access)
create policy "Gods can update any profile." on public.profiles for update using ( auth.uid() in ( select id from public.profiles where rank = 'god' ) );
create policy "Gods can view all requests." on public.admin_requests for select using ( auth.uid() in ( select id from public.profiles where rank = 'god' ) );
create policy "Gods can update requests." on public.admin_requests for update using ( auth.uid() in ( select id from public.profiles where rank = 'god' ) );
`;

export const SQL_FIX_CONSTRAINT = `
-- Hard Fix: Recreate Table (Data will be cleared)
DROP TABLE IF EXISTS public.admin_requests;

create table public.admin_requests (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id),
  full_name text,
  email text,
  type text default 'Admin Access',
  status text default 'Pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.admin_requests enable row level security;

create policy "Users can create requests." on public.admin_requests for insert with check ( auth.uid() = user_id );
create policy "Users can view their own requests." on public.admin_requests for select using ( auth.uid() = user_id );
create policy "Gods can view all requests." on public.admin_requests for select using ( auth.uid() in ( select id from public.profiles where rank = 'god' ) );
create policy "Gods can update requests." on public.admin_requests for update using ( auth.uid() in ( select id from public.profiles where rank = 'god' ) );
`;
