-- -----------------------------------------------------------------------------
-- SQL ASTRO FEATURE: Gallery, Studio, and Permissions
-- Run this to setup the Content table and Storage policies
-- -----------------------------------------------------------------------------

-- 0. HELPER: Check for God or Astrophotography Head permissions
-- Logic: User is 'god' OR (department='Astrophotography' AND rank is 'elite' or 'legendary')
create or replace function public.is_astro_privileged()
returns boolean as $$
begin
  return exists (
    select 1 from public.profiles
    where id = auth.uid()
    and (
      rank = 'god'
      or
      (department = 'Astrophotography' and rank in ('elite', 'legendary'))
    )
  );
end;
$$ language plpgsql security definer;

-- -----------------------------------------------------------------------------
-- 1. STORAGE: Create Bucket 'astro_gallery'
-- -----------------------------------------------------------------------------
-- Attempt to create the bucket if it doesn't exist
insert into storage.buckets (id, name, public)
values ('astro_gallery', 'astro_gallery', true)
on conflict (id) do nothing;

-- STORAGE POLICIES (Drop existing to be safe)
drop policy if exists "Astro Public View" on storage.objects;
drop policy if exists "Astro Privileged Upload" on storage.objects;
drop policy if exists "Astro Privileged Delete" on storage.objects;

-- 1. Everyone can view photos in this bucket
create policy "Astro Public View"
on storage.objects for select
using ( bucket_id = 'astro_gallery' );

-- 2. Only Gods & Astro Heads can upload
create policy "Astro Privileged Upload"
on storage.objects for insert
with check (
  bucket_id = 'astro_gallery'
  AND
  public.is_astro_privileged()
);

-- 3. Only Gods & Astro Heads can delete
create policy "Astro Privileged Delete"
on storage.objects for delete
using (
  bucket_id = 'astro_gallery'
  AND
  public.is_astro_privileged()
);

-- -----------------------------------------------------------------------------
-- 2. DATABASE: Create 'content' table for Posts/Studio
-- -----------------------------------------------------------------------------
create table if not exists public.content (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  image_url text not null,
  author_id uuid references public.profiles(id) not null default auth.uid(),
  section text not null, -- 'astrophotography' (public), 'astro_studio' (private)
  tags text[], -- Array of tags e.g. ['legendary']
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.content enable row level security;

-- POLICIES for 'content' table

-- 1. SELECT: 
--    - 'astro_studio' section -> Visible ONLY to Privileged Users
--    - Other sections (e.g. 'astrophotography') -> Visible to EVERYONE
drop policy if exists "View Content" on public.content;
create policy "View Content"
on public.content for select
using (
  (section = 'astro_studio' AND public.is_astro_privileged())
  OR
  (section != 'astro_studio')
);

-- 2. INSERT: Only Privileged USERS can create posts anywhere
drop policy if exists "Insert Content" on public.content;
create policy "Insert Content"
on public.content for insert
with check (
  public.is_astro_privileged()
);

-- 3. UPDATE/DELETE: Only Privileged USERS
drop policy if exists "Manage Content" on public.content;
create policy "Manage Content"
on public.content for all
using (
  public.is_astro_privileged()
);
