-- -----------------------------------------------------------------------------
-- SQL PERMISSIONS FIX (Storage + Database)
-- Run this to resolve "row-level security policy" errors when uploading.
-- -----------------------------------------------------------------------------

-- PART 1: FIX STORAGE UPLOADS (The error you are seeing)
-- This allows any logged-in user to upload to the 'astro_gallery' bucket.

update storage.buckets
set public = true
where id = 'astro_gallery';

drop policy if exists "Allow Authenticated Uploads" on storage.objects;

create policy "Allow Authenticated Uploads"
on storage.objects for insert
to authenticated
with check ( bucket_id = 'astro_gallery' );

-- Allow updates/deletes for own files
drop policy if exists "Allow Authenticated Updates" on storage.objects;
create policy "Allow Authenticated Updates"
on storage.objects for update
to authenticated
using ( bucket_id = 'astro_gallery' AND auth.uid() = owner );

drop policy if exists "Allow Authenticated Deletes" on storage.objects;
create policy "Allow Authenticated Deletes"
on storage.objects for delete
to authenticated
using ( bucket_id = 'astro_gallery' AND auth.uid() = owner );


-- PART 2: FIX DATABASE INSERTS (The next step after upload)
-- This allows logged-in users to save the file metadata to the 'content' table.
-- Without this, the upload might succeed but the post won't appear.

-- Ensure the table exists and has RLS enabled
create table if not exists public.content (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  image_url text not null,
  author_id uuid references public.profiles(id) not null default auth.uid(),
  section text not null,
  tags text[],
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.content enable row level security;

-- Add a policy to allow inserts for authenticated users
drop policy if exists "Allow Authenticated Insert Content" on public.content;

create policy "Allow Authenticated Insert Content"
on public.content for insert
to authenticated
with check ( true );

-- Add a policy to allow viewing content (if not already set)
-- This ensures the user can see what they just uploaded
drop policy if exists "Allow Authenticated Select Content" on public.content;

create policy "Allow Authenticated Select Content"
on public.content for select
to authenticated
using ( true );

