
-- Create a table for public profiles if it doesn't exist
create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  avatar_url text,
  rank text default 'common',
  sub_rank text, -- 'Zeus', 'Apollo', 'Poseidon'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.profiles enable row level security;

-- Policies for profiles
create policy "Public profiles are viewable by everyone."
  on public.profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on public.profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on public.profiles for update
  using ( auth.uid() = id );

-- Create a table for admin requests
create table if not exists public.admin_requests (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id),
  full_name text,
  email text,
  type text default 'Admin Access',
  status text default 'Pending', -- 'Pending', 'Approved', 'Rejected'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.admin_requests enable row level security;

-- Policies for admin_requests
create policy "Users can create requests."
  on public.admin_requests for insert
  with check ( auth.uid() = user_id );

create policy "Users can view their own requests."
  on public.admin_requests for select
  using ( auth.uid() = user_id );

-- SPECIAL POLICY: Give Poseidon full access (Hardcoded email check if possible, or manual DB admin)
-- Ideally, you manage this via a 'ranks' check, but for now we create a permissive policy for the 'god' rank or specific email.
-- Since we can't easily check email in simple policies without joining auth.users which has security implications, 
-- we will allow anyone with rank 'god' to update profiles.

create policy "Gods can update any profile."
  on public.profiles for update
  using ( 
    auth.uid() in (
      select id from public.profiles where rank = 'god'
    )
  );

create policy "Gods can view all requests."
  on public.admin_requests for select
  using ( 
    auth.uid() in (
      select id from public.profiles where rank = 'god'
    )
  );

create policy "Gods can update requests."
  on public.admin_requests for update
  using ( 
    auth.uid() in (
      select id from public.profiles where rank = 'god'
    )
  );

-- Trigger to create profile on signup (Optional but recommended)
-- You would run this in the SQL editor:
/*
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
*/
